(define (problem block_problem)
(:domain blocks_problem)
(:objects A B C)
(:init (On A C)
    (Ontable B)
    (Ontable C)
    (Clear A)
    (Clear B)
    (Armfree))
(:goal (and (On A B) 
       (On B C)))
)